version: "3.9"

services:
    kafka-rust-consumer:
        container_name: kafka-rust-consumer
        build:
            context: ../../../
            dockerfile: ./.devops/docker/develop/Dockerfile
        volumes:
            - ../../..:/home/app
        networks:
            - app-network
            - kafka-network
networks:
    app-network:
        driver: bridge
    kafka-network:
        external: true